### PR TITLE
updated openapigenerator to v5.0.1

### PR DESCRIPTION
**Pull request by MichaelMraka**
and regenerated clients

### CODE REVIEW

**Comment by MichaelMraka** [comment]
fixed date types

**Review by Josca — CHANGES_REQUESTED** [review]
Ok, it works. However I ran `./generate-clients.sh --docker` and it produced many changes in generated *.md and *.go files. Have you really re-generated the clients?

**Comment by MichaelMraka** [comment]
sure, but they are fast moving targets

**Review by Josca — APPROVED** [review]
lgtm

**Pull request merged**
